### ISSUE TITLE
Lag navigasjon med react router

### ISSUE THREAD

**Issue by elisetelje** [BG4-22/GREENK#5]
**Hva:**
Kort beskrivelse og bullet points om hva som skal med

**Hvordan**
Verktøy man kan bruke og plan for implementering

┆Issue is synchronized with this [Trello card](https://trello.com/c/YGEnQJvv) by [Unito](https://www.unito.io)

**Comment by sigbbe** [comment]
- [ ] Legg til avhengighet i package.json
- [ ] Sett opp mappestruktur
- [ ] Legg til rutene i <App />
